import Link from "next/link";

export const metadata = {
  title: "Marketing Layout",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "#f2f2f2" }}>
          <h1>Header</h1>
          <nav>
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/products">Products</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main>
          <h1>Root Layout</h1>
          <p>This is the root layout.</p>
          {children}
        </main>
        <footer style={{ marginTop: "auto", backgroundColor: "#f1f1f1" }}>
          <h1>Footer</h1>
          <p>This is the footer.</p>
          <nav>
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/products">Products</Link>
              </li>
              <li>
                <Link href="/login">Login</Link>
              </li>
              <li>
                <Link href="/forget-password">Forget Password</Link>
              </li>
            </ul>
          </nav>
        </footer>
      </body>
    </html>
  );
}
